apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: uniia-landing-production
  namespace: fleet-local
spec:
  # Репозиторій, який буде відслідковуватись Fleet
  repo: https://github.com/uniia-com-ua/turbo-frontend
  # Гілка, яку буде відслідковувати Fleet
  branch: main
  # Шлях до директорії з Fleet конфігурацією в репозиторії
  paths:
  - apps/landing/fleet/production
  # Інтервал синхронізації (за замовчуванням 15m)
  pollingInterval: 1m 