apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../resources

namespace: web-landing-prod

images:
- name: ghcr.io/uniia-com-ua/uniia-landing
  newTag: latest

patchesStrategicMerge:
- patch-deployment.yaml 