name: Збірка та розгортання релізу

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine app and set variables
        id: determine-app
        run: |
          TAG=${{ github.event.release.tag_name }}
          IS_PRERELEASE=${{ github.event.release.prerelease }}
          IS_RC=${{ contains(github.event.release.tag_name, '-rc') }}
          
          # Визначаємо застосунок за префіксом
          if [[ "$TAG" == landing-* ]]; then
            # Landing застосунок
            APP_NAME="landing"
            APP_PATH="apps/landing"
            VERSION=$(echo $TAG | sed 's/landing-//')
          # Додайте інші застосунки тут
          # elif [[ "$TAG" == admin-* ]]; then
          #   APP_NAME="admin"
          #   APP_PATH="apps/admin"
          #   VERSION=$(echo $TAG | sed 's/admin-//')
          # elif [[ "$TAG" == api-* ]]; then
          #   APP_NAME="api"
          #   APP_PATH="apps/api"
          #   VERSION=$(echo $TAG | sed 's/api-//')
          else
            # Якщо префікс не знайдено, використовуємо старий формат (тільки для landing)
            APP_NAME="landing"
            APP_PATH="apps/landing"
            VERSION=$TAG
            echo "УВАГА: Не знайдено префікс застосунку в тегу $TAG. Використовуємо landing за замовчуванням."
          fi
          
          # Налаштовуємо змінні середовища
          if [[ "$IS_PRERELEASE" == "true" || "$IS_RC" == "true" || "$VERSION" == *"-rc"* ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
            echo "ENV_TAG=latest-rc" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "ENV_TAG=latest" >> $GITHUB_ENV
          fi
          
          # Зберігаємо визначені змінні
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
          
          echo "Застосунок: $APP_NAME"
          echo "Шлях до застосунку: $APP_PATH"
          echo "Версія: $VERSION"
          echo "Середовище: ${{ env.ENVIRONMENT }}"
          echo "Тег образу: ${{ env.ENV_TAG }}"

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/uniia-${{ env.APP_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest,enable=${{ !contains(env.VERSION, '-rc') && !github.event.release.prerelease }}
            type=raw,value=latest-rc,enable=${{ contains(env.VERSION, '-rc') || github.event.release.prerelease }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ env.APP_PATH }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary of release
        run: |
          echo "Застосунок: ${{ env.APP_NAME }}"
          echo "Реліз: ${{ env.RELEASE_TAG }}"
          echo "Версія: ${{ env.VERSION }}"
          echo "Середовище розгортання: ${{ env.ENVIRONMENT }}"
          echo "Тег образу: ${{ env.ENV_TAG }}"

  update-fleet-config:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Determine app and set variables
        id: determine-app
        run: |
          TAG=${{ github.event.release.tag_name }}
          IS_PRERELEASE=${{ github.event.release.prerelease }}
          IS_RC=${{ contains(github.event.release.tag_name, '-rc') }}
          
          # Визначаємо застосунок за префіксом
          if [[ "$TAG" == landing-* ]]; then
            # Landing застосунок
            APP_NAME="landing"
            APP_PATH="apps/landing"
            VERSION=$(echo $TAG | sed 's/landing-//')
          # Додайте інші застосунки тут
          # elif [[ "$TAG" == admin-* ]]; then
          #   APP_NAME="admin"
          #   APP_PATH="apps/admin"
          #   VERSION=$(echo $TAG | sed 's/admin-//')
          # elif [[ "$TAG" == api-* ]]; then
          #   APP_NAME="api"
          #   APP_PATH="apps/api"
          #   VERSION=$(echo $TAG | sed 's/api-//')
          else
            # Якщо префікс не знайдено, використовуємо старий формат (тільки для landing)
            APP_NAME="landing"
            APP_PATH="apps/landing"
            VERSION=$TAG
            echo "УВАГА: Не знайдено префікс застосунку в тегу $TAG. Використовуємо landing за замовчуванням."
          fi
          
          # Налаштовуємо змінні середовища
          if [[ "$IS_PRERELEASE" == "true" || "$IS_RC" == "true" || "$VERSION" == *"-rc"* ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
            echo "ENV_TAG=latest-rc" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "ENV_TAG=latest" >> $GITHUB_ENV
          fi
          
          # Зберігаємо визначені змінні
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
      
      - name: Create branch for changes
        run: |
          BRANCH_NAME="fleet-update-${{ env.APP_NAME }}-${{ env.VERSION }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      
      - name: Update Fleet configuration
        run: |
          # Переконуємося, що директорія існує
          if [ ! -d "${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}" ]; then
            echo "Помилка: Директорія ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }} не існує!"
            exit 1
          fi
          
          # Перевіряємо існування файлу kustomization.yaml
          if [ ! -f "${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml" ]; then
            echo "Помилка: Файл kustomization.yaml не знайдено в директорії ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}!"
            exit 1
          fi
          
          # Оновлюємо тег образу в конфігурації Fleet для відповідного середовища
          # Використовуємо конкретну версію релізу
          sed -i "s/newTag: .*$/newTag: ${{ env.VERSION }}/" ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          
          # Виводимо зміни для логування
          echo "Оновлено kustomization.yaml в директорії ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}:"
          cat ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          
          # Зберігаємо зміни
          git add ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          git commit -m "Оновлено Fleet конфігурацію для ${{ env.APP_NAME }} до версії ${{ env.VERSION }}"
          git push origin ${{ env.BRANCH_NAME }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: false
          title: "Оновлення Fleet конфігурації для ${{ env.APP_NAME }} до версії ${{ env.VERSION }}"
          body: |
            Автоматичне оновлення Fleet конфігурації для розгортання ${{ env.APP_NAME }} версії ${{ env.VERSION }}.
            
            **Застосунок:** ${{ env.APP_NAME }}
            **Середовище:** ${{ env.ENVIRONMENT }}
            **Тег образу:** ${{ env.VERSION }}
            
            Цей PR було створено автоматично через GitHub Actions після публікації релізу. 