name: Збірка та розгортання релізу

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      app_name: ${{ steps.determine-app.outputs.app_name }}
      app_path: ${{ steps.determine-app.outputs.app_path }}
      version: ${{ steps.determine-app.outputs.version }}
      environment: ${{ steps.determine-app.outputs.environment }}
      env_tag: ${{ steps.determine-app.outputs.env_tag }}
      release_tag: ${{ steps.determine-app.outputs.release_tag }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine app and set variables
        id: determine-app
        run: |
          TAG=${{ github.event.release.tag_name }}
          IS_PRERELEASE=${{ github.event.release.prerelease }}
          IS_RC=${{ contains(github.event.release.tag_name, '-rc') }}
          
          echo "Тег релізу: $TAG"
          echo "IS_PRERELEASE: $IS_PRERELEASE"
          echo "IS_RC: $IS_RC"
          
          # Визначаємо застосунок за префіксом
          if [[ "$TAG" == landing-* ]]; then
            # Landing застосунок
            APP_NAME="landing"
            APP_PATH="apps/landing"
            VERSION=$(echo $TAG | sed 's/landing-//')
          # Додайте інші застосунки тут
          # elif [[ "$TAG" == admin-* ]]; then
          #   APP_NAME="admin"
          #   APP_PATH="apps/admin"
          #   VERSION=$(echo $TAG | sed 's/admin-//')
          # elif [[ "$TAG" == api-* ]]; then
          #   APP_NAME="api"
          #   APP_PATH="apps/api"
          #   VERSION=$(echo $TAG | sed 's/api-//')
          else
            # Якщо префікс не знайдено, використовуємо старий формат (тільки для landing)
            APP_NAME="landing"
            APP_PATH="apps/landing"
            VERSION=$TAG
            echo "УВАГА: Не знайдено префікс застосунку в тегу $TAG. Використовуємо landing за замовчуванням."
          fi
          
          echo "Визначені значення: APP_NAME=$APP_NAME, APP_PATH=$APP_PATH, VERSION=$VERSION"
          
          # Налаштовуємо змінні середовища
          if [[ "$IS_PRERELEASE" == "true" || "$IS_RC" == "true" || "$VERSION" == *"-rc"* ]]; then
            echo "Визначено тестове середовище (test) на основі версії $VERSION"
            ENVIRONMENT="test"
            ENV_TAG="latest-rc"
          else
            echo "Визначено продакшн середовище (production) на основі версії $VERSION"
            ENVIRONMENT="production"
            ENV_TAG="latest"
          fi
          
          # Встановлюємо outputs напряму з цього кроку
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "app_path=$APP_PATH" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "env_tag=$ENV_TAG" >> $GITHUB_OUTPUT
          echo "release_tag=$TAG" >> $GITHUB_OUTPUT
          
          # Також встановлюємо в env для подальшого використання в цьому job
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
          
          # Виводимо проміжну інформацію
          echo "---"
          echo "Встановлені змінні та outputs:"
          echo "Застосунок: $APP_NAME (output: app_name)"
          echo "Шлях до застосунку: $APP_PATH (output: app_path)"
          echo "Версія: $VERSION (output: version)"
          echo "Середовище: $ENVIRONMENT (output: environment)"
          echo "Тег образу: $ENV_TAG (output: env_tag)"
          echo "Реліз: $TAG (output: release_tag)"
          echo "---"

      # Додаємо окремий крок для діагностики
      - name: Debug Environment Variables
        run: |
          echo "Перевірка доступних змінних середовища та outputs після встановлення:"
          echo "APP_NAME: ${{ env.APP_NAME }}"
          echo "APP_PATH: ${{ env.APP_PATH }}"
          echo "VERSION: ${{ env.VERSION }}"
          echo "ENVIRONMENT: ${{ env.ENVIRONMENT }}"
          echo "ENV_TAG: ${{ env.ENV_TAG }}"
          echo "RELEASE_TAG: ${{ env.RELEASE_TAG }}"
          echo ""
          echo "Output app_name: ${{ steps.determine-app.outputs.app_name }}"
          echo "Output app_path: ${{ steps.determine-app.outputs.app_path }}"
          echo "Output version: ${{ steps.determine-app.outputs.version }}"
          echo "Output environment: ${{ steps.determine-app.outputs.environment }}"
          echo "Output env_tag: ${{ steps.determine-app.outputs.env_tag }}"
          echo "Output release_tag: ${{ steps.determine-app.outputs.release_tag }}"
          
          # Перевіряємо, чи встановлено важливі змінні
          if [ -z "${{ env.ENVIRONMENT }}" ] || [ -z "${{ env.APP_NAME }}" ] || [ -z "${{ env.VERSION }}" ]; then
            echo "ПОМИЛКА: Одна або більше необхідних змінних середовища не встановлено!"
            exit 1
          fi

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/uniia-${{ env.APP_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest,enable=${{ !contains(env.VERSION, '-rc') && !github.event.release.prerelease }}
            type=raw,value=latest-rc,enable=${{ contains(env.VERSION, '-rc') || github.event.release.prerelease }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ env.APP_PATH }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary of release
        run: |
          echo "Застосунок: ${{ env.APP_NAME }}"
          echo "Реліз: ${{ env.RELEASE_TAG }}"
          echo "Версія: ${{ env.VERSION }}"
          echo "Середовище розгортання: ${{ env.ENVIRONMENT }}"
          echo "Тег образу: ${{ env.ENV_TAG }}"
          echo ""
          echo "Job outputs:"
          echo "app_name: ${{ steps.determine-app.outputs.app_name }}"
          echo "version: ${{ steps.determine-app.outputs.version }}"
          echo "environment: ${{ steps.determine-app.outputs.environment }}"

  update-fleet-config:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Print output parameters
        run: |
          echo "Outputs з попереднього job:"
          echo "app_name: ${{ needs.build-and-push.outputs.app_name }}"
          echo "app_path: ${{ needs.build-and-push.outputs.app_path }}"
          echo "version: ${{ needs.build-and-push.outputs.version }}"
          echo "environment: ${{ needs.build-and-push.outputs.environment }}"
          echo "env_tag: ${{ needs.build-and-push.outputs.env_tag }}"
          echo "release_tag: ${{ needs.build-and-push.outputs.release_tag }}"
          
      - name: Set environment variables from needs
        run: |
          # Безпосередньо використовуємо outputs у командах
          APP_NAME="${{ needs.build-and-push.outputs.app_name }}"
          APP_PATH="${{ needs.build-and-push.outputs.app_path }}"
          VERSION="${{ needs.build-and-push.outputs.version }}"
          ENVIRONMENT="${{ needs.build-and-push.outputs.environment }}"
          ENV_TAG="${{ needs.build-and-push.outputs.env_tag }}"
          RELEASE_TAG="${{ needs.build-and-push.outputs.release_tag }}"
          
          # Зберігаємо в GITHUB_ENV для подальших кроків
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          
          echo "Змінні середовища встановлені з outputs першого job:"
          echo "APP_NAME: $APP_NAME"
          echo "APP_PATH: $APP_PATH"
          echo "VERSION: $VERSION"
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "ENV_TAG: $ENV_TAG"
          echo "RELEASE_TAG: $RELEASE_TAG"
          
          # Перевіряємо одразу тут, не використовуючи ${{ env.XXX }}
          if [ -z "$APP_NAME" ] || [ -z "$APP_PATH" ] || [ -z "$VERSION" ] || [ -z "$ENVIRONMENT" ]; then
            echo "ПОМИЛКА: Одна або більше необхідних змінних середовища не встановлено з outputs!"
            exit 1
          fi
      
      - name: Create branch for changes
        run: |
          BRANCH_NAME="fleet-update-${{ env.APP_NAME }}-${{ env.VERSION }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      
      - name: Update Fleet configuration
        run: |
          # Переконуємося, що директорія існує
          if [ ! -d "${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}" ]; then
            echo "Помилка: Директорія ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }} не існує!"
            exit 1
          fi
          
          # Перевіряємо існування файлу kustomization.yaml
          if [ ! -f "${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml" ]; then
            echo "Помилка: Файл kustomization.yaml не знайдено в директорії ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}!"
            exit 1
          fi
          
          # Виводимо поточний стан файлу для логування
          echo "Поточний стан kustomization.yaml:"
          cat ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          
          # Оновлюємо тег образу в конфігурації Fleet для відповідного середовища
          # Використовуємо версію релізу замість постійних тегів
          NEW_TAG="${{ env.VERSION }}"
          echo "Оновлюємо тег образу на: $NEW_TAG"
          
          # Використовуємо більш надійний спосіб заміни
          # Шукаємо рядок з 'newTag:' і замінюємо все після нього на новий тег
          sed -i '/newTag:/ s/newTag:.*$/newTag: '"$NEW_TAG"'/' ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          
          # Виводимо оновлений стан для перевірки
          echo "Оновлений kustomization.yaml:"
          cat ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          
          # Перевіряємо, чи відбулася зміна
          if git diff --quiet ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml; then
            echo "УВАГА: Зміни не були застосовані до файлу kustomization.yaml!"
            echo "Це може бути через проблеми з форматом файлу або регулярним виразом sed."
            exit 1
          fi
          
          # Зберігаємо зміни
          git add ${{ env.APP_PATH }}/fleet/${{ env.ENVIRONMENT }}/kustomization.yaml
          git commit -m "Оновлено Fleet конфігурацію для ${{ env.APP_NAME }} до версії ${{ env.VERSION }}"
      
      - name: Push changes
        run: |
          git push -u origin ${{ env.BRANCH_NAME }}
      
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Оновлено Fleet конфігурацію для ${{ env.APP_NAME }} до версії ${{ env.VERSION }}"
          title: "Оновлення Fleet конфігурації для ${{ env.APP_NAME }} до версії ${{ env.VERSION }}"
          body: |
            Автоматичне оновлення Fleet конфігурації для розгортання ${{ env.APP_NAME }} версії ${{ env.VERSION }}.
            
            **Застосунок:** ${{ env.APP_NAME }}
            **Середовище:** ${{ env.ENVIRONMENT }}
            **Тег образу:** ${{ env.VERSION }}
            
            Цей PR було створено автоматично через GitHub Actions після публікації релізу.
          branch: ${{ env.BRANCH_NAME }}
          base: main 